/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeContainer: (typeof import('./../src/components/common/DarkModeContainer.vue'))['default'];
    DarkModeSwitch: (typeof import('./../src/components/common/DarkModeSwitch.vue'))['default'];
    HelloWorld: (typeof import('./../src/components/HelloWorld.vue'))['default'];
    HoverContainer: (typeof import('./../src/components/common/HoverContainer.vue'))['default'];
    NaiveProvider: (typeof import('./../src/components/common/NaiveProvider.vue'))['default'];
    NAvatar: (typeof import('naive-ui'))['NAvatar'];
    NBackTop: (typeof import('naive-ui'))['NBackTop'];
    NButto: (typeof import('naive-ui'))['NButto'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCheckbox: (typeof import('naive-ui'))['NCheckbox'];
    NColorPicker: (typeof import('naive-ui'))['NColorPicker'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDataTable: (typeof import('naive-ui'))['NDataTable'];
    NDatePicker: (typeof import('naive-ui'))['NDatePicker'];
    NDescriptions: (typeof import('naive-ui'))['NDescriptions'];
    NDescriptionsItem: (typeof import('naive-ui'))['NDescriptionsItem'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NDivider: (typeof import('naive-ui'))['NDivider'];
    NDrawer: (typeof import('naive-ui'))['NDrawer'];
    NDrawerContent: (typeof import('naive-ui'))['NDrawerContent'];
    NDropdown: (typeof import('naive-ui'))['NDropdown'];
    NDynamicInput: (typeof import('naive-ui'))['NDynamicInput'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NFormItem: (typeof import('naive-ui'))['NFormItem'];
    NFormItemGi: (typeof import('naive-ui'))['NFormItemGi'];
    NGradientText: (typeof import('naive-ui'))['NGradientText'];
    NGrid: (typeof import('naive-ui'))['NGrid'];
    NGridItem: (typeof import('naive-ui'))['NGridItem'];
    NImage: (typeof import('naive-ui'))['NImage'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NInputNumber: (typeof import('naive-ui'))['NInputNumber'];
    NLayout: (typeof import('naive-ui'))['NLayout'];
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent'];
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader'];
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMenu: (typeof import('naive-ui'))['NMenu'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NModal: (typeof import('naive-ui'))['NModal'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NScrollbar: (typeof import('naive-ui'))['NScrollbar'];
    NSelect: (typeof import('naive-ui'))['NSelect'];
    NSpace: (typeof import('naive-ui'))['NSpace'];
    NSwitch: (typeof import('naive-ui'))['NSwitch'];
    NTabPane: (typeof import('naive-ui'))['NTabPane'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NTooltip: (typeof import('naive-ui'))['NTooltip'];
    NUpload: (typeof import('naive-ui'))['NUpload'];
    PageWrapper: (typeof import('./../src/components/common/PageWrapper.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SystemLogo: (typeof import('./../src/components/common/SystemLogo.vue'))['default'];
  }
}
